fixed bug for risk tracker and added test
miyaliu627/learnsomething pull request #1
Opened 2023-09-22 02:46 UTC by miyaliu627

Find the bug in risktracker.cpp, which is that the updateRisk function is incorrectly updating the total risk. I have the running sum replacing the total risk instead of adding to it; wrote a test to cover trades that don’t have risks that just cancel each other out. Struggled with understanding the expected behavior of the function and should probably modify the class so that updateRisk only calculates the new trades added to the vectors instead of recalculating everything again.

2023-09-22 02:53 UTC, echavemann commented
![image](https://github.com/miyaliu627/learnsomething/assets/94627102/5b72808a-c8ae-4610-aa98-5cbca0e74e10)

2023-09-22 02:54 UTC, echavemann requested changes
tests are failing, please fix

2023-09-22 03:03 UTC, echavemann commented
can you add ss of `task test` passing?

2023-09-22 03:12 UTC, miyaliu627 commented
<img width="928" alt="Screenshot 2023-09-21 at 10 12 02 PM" src="https://github.com/miyaliu627/learnsomething/assets/107294785/cc28f8c2-aa73-4a8d-be70-6c7fff1a1e07">

2023-09-22 14:38 UTC, echavemann commented
force pushed to fix the githist -> diff is good now

2023-09-22 14:38 UTC, echavemann approved these changes

2023-09-22 14:39 UTC, echavemann commented
https://github.com/echavemann/learnsomething/commit/870ea84c2886d0b157f1c6fa473d15c736395ad1

2023-09-23 17:48 UTC, minnce commented
pls merge

2023-09-24 03:29 UTC, merged